sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get -qq update

  # for the tests
  - sudo apt-get install maven

  # for the ruby lms
  - sudo apt-get install -y ruby bundler

  # for the csharp lms
  - sudo apt-get install libunwind8
  - curl -O https://cdn.rawgit.com/dotnet/cli/rel/1.0.1/scripts/obtain/dotnet-install.sh
  - chmod +x ./dotnet-install.sh
  - ./dotnet-install.sh --version 1.0.1 --no-path
  - export PATH="$PATH:~/.dotnet"

  # for the mono/nancy lms
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  # mono has its own cacerts rather than using the system copy
  - sudo apt-get install mono-complete ca-certificates-mono nuget

script:
  - ./pre-commit.sh
  
cache:
  bundler: true
  directories:
    - $HOME/.m2
    - $HOME/.nuget/packages
