sudo: required
language: java
jdk:
  - openjdk8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install maven
  # for the ruby lms
  - sudo apt-get install -y ruby bundler
script:
  - ./test_ruby.sh
  